---
title: "Flex Dashboard"
author: "Malvika Venkataraman"
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(p8105.datasets)
library(tidyverse)
library(plotly)
```

# Data
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"),
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id,
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
    mutate(prcp = prcp/10) %>%
 select(name, id, everything())
    
#View(weather_df)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Daily Recorded Precipitation by Weather Station
```{r}
weather_df %>%
 mutate(name = forcats::fct_relevel(name, c("Waikiki_HA", "CentralPark_NY", "Waterhole_WA"))) %>%
  plot_ly(color = ~ name, y = ~prcp, type = "violin", colors = "viridis") %>%
  layout(title = "Daily Recorded Precipitation by Weather Station" , xaxis = list(title = "Location"), yaxis = list(title = "Precipitation (cm)"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Total Monthly Precipitation in Waikiki
```{r}
weather_df %>%
  separate(date, into = c("year", "month", "day"), sep = "-") %>%
  drop_na(prcp) %>%
  filter(name == "Waikiki_HA") %>%
  mutate(month = recode_factor(month, "01" = "January", "02" = "February", "03" = "March", "04" = "April", "05" = "May", "06" = "June", "07" = "July", "08" = "August", "09" = "September", "10" = "October", "11" = "November", "12" = "December")) %>%
  group_by(name, month) %>%
  summarise(total_precip = sum(prcp)) %>%
  do(p=plot_ly(., x = ~month, y = ~total_precip, color = ~month, type = "bar", colors = "magma")) %>%
  subplot(nrows = 1, shareX = TRUE, shareY = TRUE) %>%
  layout(title = "Total Monthly Precipitation in Waikiki, HI", xaxis = list(title = "Month"), yaxis = list(title = "Precipitation (cm)"))
```


### Maximum Temperature Overtime per Weather Station
```{r}
weather_df_plot = weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_wrap(. ~ name) +
  labs(title = "Maximum Temperature Overtime per Weather Station", 
       x = "Date", 
       y = "Maximum Daily Temperature (C)") + 
  scale_color_discrete(name = "Weather Station") +
  theme(axis.text.x = element_text(angle = 90))

ggplotly(weather_df_plot)
```

